"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Copy, Download, Loader2, RefreshCw } from "lucide-react";
import { useCallback, useState } from "react";

import { MarkdownViewer } from "@/components/markdown-viewer";
import { Button } from "@/components/ui/button";
import { queryKeys } from "@/lib/query-keys";
import {
  getRepositoryDocumentation,
  listRepositoryDocumentation,
  regenerateRepositoryDocumentation,
} from "@/services/repositories";
import {
  DOCUMENT_CARD_ORDER,
  DOCUMENT_TYPE_LABELS,
  type DocumentType,
  type DocumentationResponse,
} from "@/types/documentation";

interface RepositoryDocsProps {
  repositoryId: string;
  branch?: string | null;
}

export function RepositoryDocs({ repositoryId, branch }: RepositoryDocsProps) {
  const queryClient = useQueryClient();
  const [selectedType, setSelectedType] = useState<DocumentType | null>(null);
  const [actionError, setActionError] = useState<string | null>(null);

  const listQuery = useQuery({
    queryKey: queryKeys.repositoryDocumentation(repositoryId, branch),
    queryFn: () => listRepositoryDocumentation(repositoryId, branch ?? undefined),
  });

  const docQuery = useQuery({
    queryKey: queryKeys.repositoryDocumentationType(repositoryId, selectedType ?? "", branch),
    queryFn: () =>
      getRepositoryDocumentation(repositoryId, selectedType as DocumentType, branch ?? undefined),
    enabled: selectedType !== null,
  });

  const regenerateMutation = useMutation({
    mutationFn: (docType: DocumentType) =>
      regenerateRepositoryDocumentation(repositoryId, docType, branch ?? undefined),
    onSuccess: (data) => {
      void queryClient.invalidateQueries({
        queryKey: queryKeys.repositoryDocumentation(repositoryId, branch),
      });
      void queryClient.setQueryData(
        queryKeys.repositoryDocumentationType(repositoryId, data.document_type, branch),
        data,
      );
      setActionError(null);
    },
    onError: (error: Error) => {
      setActionError(error.message);
    },
  });

  const handleSelect = (docType: DocumentType) => {
    setSelectedType(docType);
    setActionError(null);
  };

  const handleCopy = useCallback(async (content: string) => {
    try {
      await navigator.clipboard.writeText(content);
    } catch {
      setActionError("Failed to copy to clipboard");
    }
  }, []);

  const handleDownload = useCallback((doc: DocumentationResponse) => {
    const blob = new Blob([doc.content], { type: "text/markdown;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement("a");
    anchor.href = url;
    anchor.download = `${doc.document_type}.md`;
    anchor.click();
    URL.revokeObjectURL(url);
  }, []);

  const typesByKey = new Map(
    (listQuery.data?.types ?? []).map((item) => [item.document_type, item]),
  );

  const activeDoc = docQuery.data;
  const isLoadingDoc = docQuery.isFetching && selectedType !== null;

  return (
    <div className="space-y-6">
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
        {DOCUMENT_CARD_ORDER.map((docType) => {
          const meta = typesByKey.get(docType);
          const isSelected = selectedType === docType;
          return (
            <button
              key={docType}
              type="button"
              onClick={() => handleSelect(docType)}
              data-selected={isSelected}
              className="rounded-2xl border bg-card p-5 text-left shadow-sm transition hover:border-violet-300 hover:shadow-md data-[selected=true]:border-violet-500 data-[selected=true]:ring-2 data-[selected=true]:ring-violet-200 dark:data-[selected=true]:ring-violet-900"
            >
              <h3 className="font-semibold">{DOCUMENT_TYPE_LABELS[docType]}</h3>
              <p className="mt-1 text-xs text-muted-foreground">
                {meta?.available
                  ? meta.generated_by === "repository"
                    ? "Using existing repository documentation"
                    : "Generated by GitSight AI"
                  : "Click to load or generate"}
              </p>
            </button>
          );
        })}
      </div>

      {selectedType && (
        <div className="rounded-2xl border bg-card shadow-sm">
          <div className="flex flex-wrap items-center justify-between gap-3 border-b px-6 py-4">
            <div>
              <h2 className="text-lg font-semibold">
                {DOCUMENT_TYPE_LABELS[selectedType]}
              </h2>
              {activeDoc && (
                <p className="text-sm text-muted-foreground">
                  {activeDoc.generated_by === "repository"
                    ? "Using existing repository documentation"
                    : "Generated by GitSight AI"}
                  {activeDoc.source_path ? ` · ${activeDoc.source_path}` : null}
                </p>
              )}
            </div>
            <div className="flex flex-wrap gap-2">
              <Button
                type="button"
                variant="outline"
                size="sm"
                disabled={!activeDoc}
                onClick={() => activeDoc && void handleCopy(activeDoc.content)}
              >
                <Copy className="mr-2 size-4" />
                Copy
              </Button>
              <Button
                type="button"
                variant="outline"
                size="sm"
                disabled={!activeDoc}
                onClick={() => activeDoc && handleDownload(activeDoc)}
              >
                <Download className="mr-2 size-4" />
                Download
              </Button>
              <Button
                type="button"
                variant="outline"
                size="sm"
                disabled={regenerateMutation.isPending}
                onClick={() => regenerateMutation.mutate(selectedType)}
              >
                {regenerateMutation.isPending ? (
                  <Loader2 className="mr-2 size-4 animate-spin" />
                ) : (
                  <RefreshCw className="mr-2 size-4" />
                )}
                Regenerate
              </Button>
            </div>
          </div>

          <div className="px-6 py-6">
            {actionError && (
              <p className="mb-4 text-sm text-rose-600 dark:text-rose-400">{actionError}</p>
            )}
            {isLoadingDoc && !activeDoc && (
              <div className="flex items-center justify-center py-12">
                <Loader2 className="size-6 animate-spin text-violet-500" />
              </div>
            )}
            {docQuery.error instanceof Error && !activeDoc && (
              <p className="text-sm text-rose-600">{docQuery.error.message}</p>
            )}
            {activeDoc && <MarkdownViewer content={activeDoc.content} />}
          </div>
        </div>
      )}
    </div>
  );
}
